/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface LincolnButton {
    /**
    * The button's background color
    */
    'bgColor': string;
    /**
    * The button's border radius
    */
    'borderRadius': string;
    /**
    * The message
    */
    'message': string;
    /**
    * The button's padding
    */
    'padding': string;
    /**
    * The button's text color
    */
    'txtColor': string;
    /**
    * The button's width
    */
    'width': string;
  }
}

declare global {


  interface HTMLLincolnButtonElement extends Components.LincolnButton, HTMLStencilElement {}
  var HTMLLincolnButtonElement: {
    prototype: HTMLLincolnButtonElement;
    new (): HTMLLincolnButtonElement;
  };
  interface HTMLElementTagNameMap {
    'lincoln-button': HTMLLincolnButtonElement;
  }
}

declare namespace LocalJSX {
  interface LincolnButton {
    /**
    * The button's background color
    */
    'bgColor'?: string;
    /**
    * The button's border radius
    */
    'borderRadius'?: string;
    /**
    * The message
    */
    'message'?: string;
    /**
    * The button's padding
    */
    'padding'?: string;
    /**
    * The button's text color
    */
    'txtColor'?: string;
    /**
    * The button's width
    */
    'width'?: string;
  }

  interface IntrinsicElements {
    'lincoln-button': LincolnButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'lincoln-button': LocalJSX.LincolnButton & JSXBase.HTMLAttributes<HTMLLincolnButtonElement>;
    }
  }
}


